project_id = "wntpldomgjutwufphnpg"

[functions.tailor-application]
verify_jwt = true

[functions.process-email]
verify_jwt = true

[functions.background-apply]
verify_jwt = true

[functions.scrape-jobs]
verify_jwt = false

[functions.gmail-oauth]
verify_jwt = false

[functions.send-email-resend]
verify_jwt = true
